config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views

# handler404 = default_views.page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/', include('account.urls')),
    path('account/', include('allauth.urls')),
    path('', include('notes.urls', namespace='notes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #
    # urlpatterns += [
    #     path(
    #         "404/",
    #         default_views.page_not_found,
    #         kwargs={"exception": Exception("Page not Found")},
    #     ),
    # ]

notes/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import TopicCreateView, TopicUpdateView, TopicListView, DashboardView, TopicDeleteView, TopicDetailView, \
    EntryDeleteView, EntryUpdateView, EntryCreateView, EntryDetailView, EntryListView

app_name = 'notes'

urlpatterns = [
    path('', login_required(DashboardView.as_view()), name='dashboard'),
]

urlpatterns += [
    path('topic/', login_required(TopicListView.as_view()), name='topic_list'),
    path('topic/detail/<int:pk>/', TopicDetailView.as_view(), name='topic_detail'),
    path('topic/create/', TopicCreateView.as_view(), name='topic_create'),
    path('topic/update/<int:pk>/', TopicUpdateView.as_view(), name='topic_update'),
    path('topic/delete/<int:pk>/', TopicDeleteView.as_view(), name='topic_delete'),
]

urlpatterns += [
    path('entry/', login_required(EntryListView.as_view()), name='entry_list'),
    path('entry/detail/<int:pk>/', EntryDetailView.as_view(), name='entry_detail'),
    path('entry/create/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/update/<int:pk>/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/delete/<int:pk>/', EntryDeleteView.as_view(), name='entry_delete'),
]

notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel


# Create your models here.


class Topic(TimeStampedModel):
    """ A Topic the user is learning about"""
    name = models.CharField(max_length=200, help_text="Enter Topic Name?")
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

    def get_create_url(self):
        return reverse("notes:topic_create")

    def get_absolute_url(self):
        return reverse("notes:topic_detail", args=(self.id,))

    def get_update_url(self):
        return reverse("notes:topic_update", args=(self.id,))

    def get_delete_url(self):
        return reverse("notes:topic_delete", args=(self.id,))


class Entry(models.Model):
    """Something Specific learned about topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Entry'
        verbose_name_plural = 'Entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        return f'{self.text[:50]}...'

    @staticmethod
    def get_create_url(self):
        return reverse("notes:entry_create")

    def get_update_url(self):
        return reverse("notes:entry_update", args=(self.id,))

    def get_absolute_url(self):
        return reverse("notes:entry_detail", args=(self.id,))

    def get_delete_url(self):
        return reverse("notes:entry_delete", args=(self.id,))

notes/forms.py
from django import forms

from notes.models import Topic, Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ["name", "owner"]


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ["topic", "text"]

notes/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, TemplateView, DeleteView, DetailView
from notes.forms import TopicForm, EntryForm
from notes.models import Topic, Entry


# Create your views here.


class DashboardView(TemplateView):
    template_name = "base.html"


class TopicListView(ListView):
    model = Topic
    template_name = "notes/topic_list.html"
    login_url = reverse_lazy('notes:dashboard')


class TopicDetailView(DetailView):
    model = Topic
    template_name = "notes/topic_detail.html"


class TopicCreateView(CreateView):
    model = Topic
    form_class = TopicForm
    template_name = "notes/topic_form.html"
    success_url = reverse_lazy("notes:topic_list")

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["back_btn_url"] = self.request.META.get("HTTP_REFERER")
        return ctx


class TopicUpdateView(UpdateView):
    model = Topic
    form_class = TopicForm
    template_name = "notes/topic_form.html"
    success_url = reverse_lazy("notes:topic_list")

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["back_btn_url"] = self.request.META.get("HTTP_REFERER")
        return ctx


class TopicDeleteView(DeleteView):
    model = Topic
    success_url = reverse_lazy("notes:topic_list")


class EntryListView(ListView):
    model = Entry
    template_name = "notes/entry_list.html"


class EntryDetailView(DetailView):
    model = Entry
    template_name = "notes/entry_detail.html"


class EntryCreateView(CreateView):
    model = Entry
    form_class = EntryForm
    template_name = "notes/Entry_form.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["back_btn_url"] = self.request.META.get("HTTP_REFERER")
        return ctx

    def get_success_url(self):
        return str(self.request.META.get("HTTP_REFERER"))


class EntryUpdateView(UpdateView):
    model = Entry
    form_class = EntryForm
    template_name = "notes/entry_form.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["back_btn_url"] = self.request.META.get("HTTP_REFERER")
        return ctx

    def get_success_url(self):
        return str(self.request.META.get("HTTP_REFERER"))


class EntryDeleteView(DeleteView):
    model = Entry

    def get_success_url(self):
        return str(self.request.META.get("HTTP_REFERER"))

templates/notes/entry_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="page-body">
    <div class="container-xl">
        <div class="card">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h3 class="card-title text-success">Entry List</h3>
                <div>
                    <a href="{% url 'notes:entry_list' %}" class="btn btn-primary">Back</a>
                    <a href="{{ object.get_update_url }}" class="btn btn-secondary">Edit</a>
                </div>
            </div>

            <div class="card-body">
                <div class="row">
                    <!-- Datagrid Item -->
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">Id</div>
                            <div class="datagrid-content">{{ object.id }}</div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">Text</div>
                            <div class="datagrid-content">{{ object.text }}</div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">Topic</div>
                            <div class="datagrid-content">{{ object.topic }}</div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">Date Added</div>
                            <div class="datagrid-content">{{ object.date_added }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/notes/entry_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div class="card">
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h3>Add New Entry</h3>
                    <a href="{{ back_btn_url }}" class="btn btn-primary">Back</a>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                        {% comment %}
                        <!-- Loop through form fields to add Bootstrap classes -->
<!--                        {% for field in form %}-->
<!--                        <div class="mb-3">-->
<!--                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}: </label>-->
<!--                            {{ field }} {{ field.help_text }}-->
<!--                            {% if field.errors %}-->
<!--                            <div class="text-danger small mt-1">-->
<!--                                {{ field.errors }}-->
<!--                            </div>-->
<!--                            {% endif %}-->
<!--                        </div>-->
<!--                        {% endfor %}-->
<!--                        <div class="d-grid">-->
<!--                            <button type="submit" class="btn btn-primary btn-block">Save</button>-->
<!--                        </div>-->
                            {% endcomment %}

                        {% bootstrap_form form %}
                        {% bootstrap_button button_type="submit" content="Add Entry" %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/notes/entry_list.html
{% extends 'base.html' %}
{% block content %}


<div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
        <h3 class="card-title text-success">Entry List</h3>
        <div class="card-actions">
            <a href="{% url 'notes:entry_create' %}" class="btn btn-primary">
                <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M12 5l0 14"></path>
                    <path d="M5 12l14 0"></path>
                </svg>
                Add entry
            </a>
        </div>
    </div>
</div>

<div class="card col-lg-12">
    <div class="table-responsive">
        <table class="table table-vcenter card-table">
            <thead>
            <tr>
                <th>Topic</th>
                <th>text</th>
                <th>Date_modified</th>
                <th>Detail</th>
                <th>Update</th>
                <th class="w-1">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for entry in object_list %}
            <tr>
                <td>{{ entry.topic }}</td>
                <td class="text-secondary">
                    {{ entry.text }}
                <td class="text-secondary">
                    {{ entry.date_added }}
                </td>
                <td class="text-secondary"><a href="{{ entry.get_absolute_url }}" class="text-reset">
                    Detail</a></td>
                <td class="text-secondary">
                    <a href="{{ entry.get_update_url }}">Update</a>
                </td>
                <td>
                    <form action="{{ entry.get_delete_url }}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/notes/topic_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="page-body">
    <div class="container-xl">
        <div class="card">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h3 class="card-title text-success">{{ object.name }}</h3>
                <div>
                    <a href="{% url 'notes:topic_list' %}" class="btn btn-primary">Back</a>
                    <a href="{{ object.get_update_url }}" class="btn btn-secondary">Edit</a>
                </div>
            </div>

            <div class="card-body">
                <div class="row">
                    <!-- Datagrid Item -->
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">Name</div>
                            <div class="datagrid-content">{{ object.name }}</div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">Created</div>
                            <div class="datagrid-content">{{ object.created }}</div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">Modified</div>
                            <div class="datagrid-content">{{ object.modified }}</div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-6">
                        <div class="datagrid-item">
                            <div class="datagrid-title">id</div>
                            <div class="datagrid-content">{{ object.id }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% if object.entry_set.exists %}
        <div class="card mt-5">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h3 class="card-title"><strong class="text-danger">Entries</strong></h3>
                <div class="card-actions">
                    <a href="{% url 'notes:entry_create' %}" class="btn btn-primary">Add Entry</a>
                </div>
            </div>
            <div class="card col-lg-12">
                <div class="table-responsive">
                    <table class="table table-vcenter card-table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Text</th>
                            <th>Added On</th>
                            <th>Update</th>
                            <th class="w-1">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for entry in object.entry_set.all %}
                        <tr>
                            <td>{{ entry.id }}</td>
                            <td class="text-secondary">
                                {{ entry.text }}
                            <td class="text-secondary">
                                {{ entry.date_added }}
                            </td>
                            <td class="text-secondary"><a href="{{ entry.get_update_url }}" class="text-reset">
                                Update</a></td>
                            <td>
                                <form action="{{ entry.get_delete_url}}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% else %}
        <div class="card mt-5">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h3 class="card-title"><strong class="text-danger">No Entries</strong></h3>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/notes/topic_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div class="card">
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h3>Add New Topic</h3>
                    <a href="{{ back_btn_url }}" class="btn btn-primary">Back</a>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                        {% comment %}
                        <!-- Loop through form fields to add Bootstrap classes -->
<!--                        {% for field in form %}-->
<!--                        <div class="mb-3">-->
<!--                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}: </label>-->
<!--                            {{ field }} {{ field.help_text }}-->
<!--                            {% if field.errors %}-->
<!--                            <div class="text-danger small mt-1">-->
<!--                                {{ field.errors }}-->
<!--                            </div>-->
<!--                            {% endif %}-->
<!--                        </div>-->
<!--                        {% endfor %}-->
<!--                        <div class="d-grid">-->
<!--                            <button type="submit" class="btn btn-primary btn-block">Save</button>-->
<!--                        </div>-->
                        {% endcomment %}

                        {% bootstrap_form form %}
                        {% bootstrap_button button_type="submit" content="Add Topic" %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/notes/topic_list.html
{% extends 'base.html' %}
{% block content %}


<div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
        <h3 class="card-title text-success">Django Projects List</h3>
        <div class="card-actions">
            <a href="{% url 'notes:topic_create' %}" class="btn btn-primary">
                <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M12 5l0 14"></path>
                    <path d="M5 12l14 0"></path>
                </svg>
                Add Topic
            </a>
        </div>
    </div>
</div>

<div class="card col-lg-12">
    <div class="table-responsive">
        <table class="table table-vcenter card-table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Owner</th>
                <th>Created</th>
                <th>Modified</th>
                <th>Detail</th>
                <th>Update</th>
                <th class="w-1">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for topic in object_list %}
            <tr>
                <td>{{ topic.name }}</td>
                <td>{{ topic.owner }}</td>
                <td class="text-secondary">
                    {{ topic.created }}
                <td class="text-secondary">
                    {{ topic.modified }}
                </td>
                <td class="text-secondary"><a href="{{ topic.get_absolute_url }}" class="text-reset">
                    Detail</a></td>
                <td class="text-secondary">
                    <a href="{{ topic.get_update_url }}">Update</a>
                </td>
                <td>
                    <form action="{{ topic.get_delete_url }}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}