config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views

# handler404 = default_views.page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('account/', include('account.urls')),
    path('account/', include('allauth.urls')),
    path('', include('notes.urls', namespace='notes')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #
    # urlpatterns += [
    #     path(
    #         "404/",
    #         default_views.page_not_found,
    #         kwargs={"exception": Exception("Page not Found")},
    #     ),
    # ]

notes/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import TopicCreateView, TopicUpdateView, TopicListView, DashboardView, TopicDeleteView, TopicDetailView, \
    EntryDeleteView, EntryUpdateView, EntryCreateView, EntryDetailView, EntryListView

app_name = 'notes'

urlpatterns = [
    path('', login_required(DashboardView.as_view()), name='dashboard'),
]

urlpatterns += [
    path('topic/', login_required(TopicListView.as_view()), name='topic_list'),
    path('topic/detail/<int:pk>/', TopicDetailView.as_view(), name='topic_detail'),
    path('topic/create/', TopicCreateView.as_view(), name='topic_create'),
    path('topic/update/<int:pk>/', TopicUpdateView.as_view(), name='topic_update'),
    path('topic/delete/<int:pk>/', TopicDeleteView.as_view(), name='topic_delete'),
]

urlpatterns += [
    path('entry/', login_required(EntryListView.as_view()), name='entry_list'),
    path('entry/detail/<int:pk>/', EntryDetailView.as_view(), name='entry_detail'),
    path('entry/create/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/update/<int:pk>/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/delete/<int:pk>/', EntryDeleteView.as_view(), name='entry_delete'),
]

templates/base.html
{% load static %}
{% load account %}
{% load compress %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard Sidebar</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    {% compress css %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    {% endcompress %}
</head>
<body>
<div class="dashboard">
    <!-- Sidebar -->
    <aside class="sidebar">
        <div class="sidebar-header">
            <h2><a class="fw-bold text-decoration-none text-dark" href="{{HOME_URL}}">Project Log</a>
            </h2>
            <button class="toggle-btn" onclick="toggleSidebar()">☰</button>
        </div>
        <ul class="menu">
            <li><a href="{% url 'notes:topic_list' %}">Django Projects</a></li>
            <li><a href="{% url 'notes:entry_list' %}">Project Entries</a></li>
        </ul>


        <div class="d-flex flex-column align-items-center justify-content-between mx-2 mb-2">
            {% if user.is_authenticated %}
            <p class="mb-3">Hello, {{ user.get_username }}.</p>
            <hr class="w-100"/>
            <form action="{% url 'account_logout' %}" method='post' class="w-100">
                {% csrf_token %}
                <button class="btn btn-primary w-100 mb-2" name='submit'>
                    Log out
                </button>
            </form>
            {% else %}
            <a class="btn btn-primary w-100 mb-2" href="{% url 'account_login' %}">Log in</a>
            <a class="btn btn-primary w-100 mb-2" href="{% url 'account_signup' %}">Signup</a>
            {% endif %}
        </div>
    </aside>

    <!-- Main Content -->

    <main class="content">

        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}
        {% block page_header %}
        <div class="p-3 mb-4 bg-light border rounded-3">
            <div class="container-fluid py-4">
                <h1 class="display-3">Welcome to the Dashboard.</h1>
                <p class="lead">Make your own Learning Log, and keep a list of the
                topics you're learning about. Whenever you learn something new
                about a topic, make an entry summarizing what you've learned.</p>
                Styling and Deploying an App 441
                <a class="btn btn-primary btn-lg mt-1" href="{{HOME_URL}}">Home</a>
            </div>
        </div>
        {% endblock page_header %}
        {% endblock %}
    </main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    function toggleSidebar() {
        document.querySelector('.sidebar').classList.toggle('collapsed');
    }
</script>

{% block additionalJS %}
{% endblock additionalJS %}
</body>
</html>